Text_PictureBookShelf:
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf:
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "Knick-knacks, baubles, trinkets;\n"
	.string "All kinds of souvenirs."

Text_Blueprint:
	.string "$ blueprint of some sort?\n"
	.string "It's too complicated!$"
